indoor_detections: outputs/home_test/indoor_detections.pkl
indoor_scene_ply: outputs/home_test/indoor_scene.ply
outdoor_detections: outputs/home_test/outdoor_detections.pkl
outdoor_scene_ply: outputs/home_test/outdoor_scene.ply

output_dir: outputs/home_test
output_name: aligned

estimate_scale: true
normalize_distance: true
max_cost: 5.0
